
spring:
  cloud:
    config:
      name: web-admin-feigin #需要从github上服务的资源名称，注意没有yml后缀
      profile: dev  #本次访问的配置项
      label: master
      uri: http://localhost:8888 #本次服务启动后，先去找3344服务，通过SpringCloudConfig获取github上的配置
